export const sampleCircuit = {
  title: "손 가까이 대면 LED 켜기",
  parts: [
    {
      id: "arduino",
      label: "Arduino Uno",
      componentKey: "arduino-uno-r3",
      position: { x: 80, y: 160 },
      width: 260,
    },
    {
      id: "sensor",
      label: "HC-SR04 거리 센서",
      componentKey: "hc-sr04",
      position: { x: 470, y: 70 },
      width: 240,
    },
    {
      id: "led",
      label: "LED",
      componentKey: "led-5mm-blue",
      position: { x: 460, y: 310 },
      width: 120,
    },
    {
      id: "resistor",
      label: "220Ω 저항",
      componentKey: "resistor-220-ohm",
      position: { x: 720, y: 340 },
      width: 160,
    },
  ],
  connections: [
    {
      id: "e1",
      source: "arduino",
      sourcePin: "5V",
      target: "sensor",
      targetPin: "VCC",
      label: "5V → VCC",
      labelDx: -8,
      labelDy: -24,
      color: "#dc2626",
    },
    {
      id: "e2",
      source: "sensor",
      sourcePin: "GND",
      target: "arduino",
      targetPin: "GND_P1",
      label: "GND → GND",
      labelDx: 0,
      labelDy: 24,
      color: "#1f2937",
    },
    {
      id: "e3",
      source: "arduino",
      sourcePin: "D9",
      target: "sensor",
      targetPin: "TRIG",
      label: "D9 → TRIG",
      labelDx: 0,
      labelDy: -22,
      color: "#2563eb",
    },
    {
      id: "e4",
      source: "sensor",
      sourcePin: "ECHO",
      target: "arduino",
      targetPin: "D10",
      label: "ECHO → D10",
      labelDx: 0,
      labelDy: 14,
      color: "#2563eb",
    },
    {
      id: "e5",
      source: "arduino",
      sourcePin: "D3",
      target: "led",
      targetPin: "ANODE",
      label: "D3 → ANODE",
      labelDx: 0,
      labelDy: -14,
      color: "#7c3aed",
    },
    {
      id: "e6",
      source: "led",
      sourcePin: "CATHODE",
      target: "resistor",
      targetPin: "LEAD_A",
      label: "CATHODE → 저항",
      labelDx: 0,
      labelDy: -14,
      color: "#f97316",
    },
    {
      id: "e7",
      source: "resistor",
      sourcePin: "LEAD_B",
      target: "arduino",
      targetPin: "GND_D",
      label: "저항 → GND",
      labelDx: 0,
      labelDy: 18,
      color: "#1f2937",
    },
  ],
};
