insert into public.circuit_component_assets (
  slug,
  display_name,
  category,
  board_family,
  description,
  grid_width,
  grid_height,
  pixel_width,
  pixel_height,
  license_status,
  trademark_notes,
  status
)
values
  ('arduino-uno-r3', 'Arduino Uno R3', 'controller', 'arduino', 'Uno-compatible board footprint.', 12, 8, 760, 460, 'needs_review', 'Use self-generated compatible-board artwork. Remove Arduino infinity logo and vendor marks.', 'ready'),
  ('arduino-nano', 'Arduino Nano', 'controller', 'arduino', 'Nano-compatible board footprint.', 10, 4, 620, 220, 'needs_review', 'Use generic Nano-compatible artwork without protected branding.', 'ready'),
  ('raspberry-pi-4b', 'Raspberry Pi 4B', 'controller', 'raspberry-pi', '40-pin GPIO header footprint.', 11, 7, 650, 390, 'needs_review', 'Use original artwork and verify Raspberry Pi trademark usage before public release.', 'ready'),
  ('led-5mm-red', 'Red LED 5mm', 'output', null, 'Two-leg LED.', 2, 3, 160, 220, 'approved', null, 'ready'),
  ('resistor-220ohm', '220 ohm Resistor', 'passive', null, 'Two-terminal LED current-limiting resistor.', 4, 1, 300, 90, 'approved', null, 'ready'),
  ('hc-sr04', 'HC-SR04 Ultrasonic', 'sensor', null, 'Ultrasonic distance sensor.', 6, 3, 360, 160, 'approved', null, 'ready'),
  ('servo-sg90', 'SG90 Micro Servo', 'actuator', null, 'Three-wire micro servo with signal, power, and ground leads.', 4, 4, 260, 260, 'approved', null, 'ready'),
  ('pushbutton-6x6', '6x6 Tactile Pushbutton', 'input', null, 'Four-leg tactile switch intended for breadboard placement.', 2, 2, 170, 150, 'approved', null, 'ready'),
  ('dht11', 'DHT11 Sensor', 'sensor', null, 'Temperature and humidity sensor module.', 3, 4, 200, 220, 'approved', null, 'ready'),
  ('breadboard-half', 'Half-size Breadboard', 'prototyping', null, 'Breadboard anchor with simplified rail coordinates.', 10, 6, 620, 350, 'approved', null, 'ready')
on conflict (slug) do update
set
  display_name = excluded.display_name,
  category = excluded.category,
  board_family = excluded.board_family,
  description = excluded.description,
  grid_width = excluded.grid_width,
  grid_height = excluded.grid_height,
  pixel_width = excluded.pixel_width,
  pixel_height = excluded.pixel_height,
  license_status = excluded.license_status,
  trademark_notes = excluded.trademark_notes,
  status = excluded.status;

with pin_rows as (
  select *
  from jsonb_to_recordset($$
  [
    {"slug":"arduino-uno-r3","pin_key":"SCL","label":"SCL","signal_type":"i2c","side":"top","x_px":260,"y_px":72,"aliases":["A5"],"sort_order":0},
    {"slug":"arduino-uno-r3","pin_key":"SDA","label":"SDA","signal_type":"i2c","side":"top","x_px":286,"y_px":72,"aliases":["A4"],"sort_order":1},
    {"slug":"arduino-uno-r3","pin_key":"AREF","label":"AREF","signal_type":"analog","side":"top","x_px":332,"y_px":72,"aliases":[],"sort_order":2},
    {"slug":"arduino-uno-r3","pin_key":"GND_D","label":"GND","signal_type":"ground","side":"top","x_px":358,"y_px":72,"aliases":["GND"],"sort_order":3},
    {"slug":"arduino-uno-r3","pin_key":"D13","label":"D13/SCK","signal_type":"spi","side":"top","x_px":384,"y_px":72,"aliases":["13","SCK"],"sort_order":4},
    {"slug":"arduino-uno-r3","pin_key":"D12","label":"D12/MISO","signal_type":"spi","side":"top","x_px":410,"y_px":72,"aliases":["12","MISO"],"sort_order":5},
    {"slug":"arduino-uno-r3","pin_key":"D11","label":"D11 PWM/MOSI","signal_type":"pwm","side":"top","x_px":436,"y_px":72,"aliases":["11","MOSI"],"sort_order":6},
    {"slug":"arduino-uno-r3","pin_key":"D10","label":"D10 PWM/SS","signal_type":"pwm","side":"top","x_px":462,"y_px":72,"aliases":["10","SS"],"sort_order":7},
    {"slug":"arduino-uno-r3","pin_key":"D9","label":"D9 PWM","signal_type":"pwm","side":"top","x_px":488,"y_px":72,"aliases":["9"],"sort_order":8},
    {"slug":"arduino-uno-r3","pin_key":"D8","label":"D8","signal_type":"digital","side":"top","x_px":514,"y_px":72,"aliases":["8"],"sort_order":9},
    {"slug":"arduino-uno-r3","pin_key":"D7","label":"D7","signal_type":"digital","side":"top","x_px":560,"y_px":72,"aliases":["7"],"sort_order":10},
    {"slug":"arduino-uno-r3","pin_key":"D6","label":"D6 PWM","signal_type":"pwm","side":"top","x_px":586,"y_px":72,"aliases":["6"],"sort_order":11},
    {"slug":"arduino-uno-r3","pin_key":"D5","label":"D5 PWM","signal_type":"pwm","side":"top","x_px":612,"y_px":72,"aliases":["5"],"sort_order":12},
    {"slug":"arduino-uno-r3","pin_key":"D4","label":"D4","signal_type":"digital","side":"top","x_px":638,"y_px":72,"aliases":["4"],"sort_order":13},
    {"slug":"arduino-uno-r3","pin_key":"D3","label":"D3 PWM","signal_type":"pwm","side":"top","x_px":664,"y_px":72,"aliases":["3"],"sort_order":14},
    {"slug":"arduino-uno-r3","pin_key":"D2","label":"D2","signal_type":"digital","side":"top","x_px":690,"y_px":72,"aliases":["2"],"sort_order":15},
    {"slug":"arduino-uno-r3","pin_key":"D1","label":"D1/TX","signal_type":"uart","side":"top","x_px":716,"y_px":72,"aliases":["1","TX"],"sort_order":16},
    {"slug":"arduino-uno-r3","pin_key":"IOREF","label":"IOREF","signal_type":"power","side":"bottom","x_px":252,"y_px":386,"aliases":[],"sort_order":100},
    {"slug":"arduino-uno-r3","pin_key":"RESET","label":"RESET","signal_type":"digital","side":"bottom","x_px":278,"y_px":386,"aliases":["RST"],"sort_order":101},
    {"slug":"arduino-uno-r3","pin_key":"3V3","label":"3.3V","signal_type":"power","side":"bottom","x_px":304,"y_px":386,"aliases":[],"sort_order":102},
    {"slug":"arduino-uno-r3","pin_key":"5V","label":"5V","signal_type":"power","side":"bottom","x_px":330,"y_px":386,"aliases":[],"sort_order":103},
    {"slug":"arduino-uno-r3","pin_key":"GND_P1","label":"GND","signal_type":"ground","side":"bottom","x_px":356,"y_px":386,"aliases":["GND"],"sort_order":104},
    {"slug":"arduino-uno-r3","pin_key":"GND_P2","label":"GND","signal_type":"ground","side":"bottom","x_px":382,"y_px":386,"aliases":["GND"],"sort_order":105},
    {"slug":"arduino-uno-r3","pin_key":"VIN","label":"VIN","signal_type":"power","side":"bottom","x_px":408,"y_px":386,"aliases":[],"sort_order":106},
    {"slug":"arduino-uno-r3","pin_key":"D0","label":"D0/RX","signal_type":"uart","side":"bottom","x_px":434,"y_px":386,"aliases":["0","RX"],"sort_order":107},
    {"slug":"arduino-uno-r3","pin_key":"A0","label":"A0","signal_type":"analog","side":"bottom","x_px":516,"y_px":386,"aliases":[],"sort_order":200},
    {"slug":"arduino-uno-r3","pin_key":"A1","label":"A1","signal_type":"analog","side":"bottom","x_px":542,"y_px":386,"aliases":[],"sort_order":201},
    {"slug":"arduino-uno-r3","pin_key":"A2","label":"A2","signal_type":"analog","side":"bottom","x_px":568,"y_px":386,"aliases":[],"sort_order":202},
    {"slug":"arduino-uno-r3","pin_key":"A3","label":"A3","signal_type":"analog","side":"bottom","x_px":594,"y_px":386,"aliases":[],"sort_order":203},
    {"slug":"arduino-uno-r3","pin_key":"A4","label":"A4/SDA","signal_type":"i2c","side":"bottom","x_px":620,"y_px":386,"aliases":["SDA"],"sort_order":204},
    {"slug":"arduino-uno-r3","pin_key":"A5","label":"A5/SCL","signal_type":"i2c","side":"bottom","x_px":646,"y_px":386,"aliases":["SCL"],"sort_order":205},

    {"slug":"arduino-nano","pin_key":"D13","label":"D13/SCK","signal_type":"spi","side":"top","x_px":44,"y_px":46,"aliases":["13","SCK"],"sort_order":0},
    {"slug":"arduino-nano","pin_key":"3V3","label":"3.3V","signal_type":"power","side":"top","x_px":82,"y_px":46,"aliases":[],"sort_order":1},
    {"slug":"arduino-nano","pin_key":"AREF","label":"AREF","signal_type":"analog","side":"top","x_px":120,"y_px":46,"aliases":[],"sort_order":2},
    {"slug":"arduino-nano","pin_key":"A0","label":"A0","signal_type":"analog","side":"top","x_px":158,"y_px":46,"aliases":[],"sort_order":3},
    {"slug":"arduino-nano","pin_key":"A1","label":"A1","signal_type":"analog","side":"top","x_px":196,"y_px":46,"aliases":[],"sort_order":4},
    {"slug":"arduino-nano","pin_key":"A2","label":"A2","signal_type":"analog","side":"top","x_px":234,"y_px":46,"aliases":[],"sort_order":5},
    {"slug":"arduino-nano","pin_key":"A3","label":"A3","signal_type":"analog","side":"top","x_px":272,"y_px":46,"aliases":[],"sort_order":6},
    {"slug":"arduino-nano","pin_key":"A4","label":"A4/SDA","signal_type":"i2c","side":"top","x_px":310,"y_px":46,"aliases":["SDA"],"sort_order":7},
    {"slug":"arduino-nano","pin_key":"A5","label":"A5/SCL","signal_type":"i2c","side":"top","x_px":348,"y_px":46,"aliases":["SCL"],"sort_order":8},
    {"slug":"arduino-nano","pin_key":"A6","label":"A6","signal_type":"analog","side":"top","x_px":386,"y_px":46,"aliases":[],"sort_order":9},
    {"slug":"arduino-nano","pin_key":"A7","label":"A7","signal_type":"analog","side":"top","x_px":424,"y_px":46,"aliases":[],"sort_order":10},
    {"slug":"arduino-nano","pin_key":"5V","label":"5V","signal_type":"power","side":"top","x_px":462,"y_px":46,"aliases":[],"sort_order":11},
    {"slug":"arduino-nano","pin_key":"RESET_1","label":"RESET","signal_type":"digital","side":"top","x_px":500,"y_px":46,"aliases":["RST","RESET"],"sort_order":12},
    {"slug":"arduino-nano","pin_key":"GND_1","label":"GND","signal_type":"ground","side":"top","x_px":538,"y_px":46,"aliases":["GND"],"sort_order":13},
    {"slug":"arduino-nano","pin_key":"VIN","label":"VIN","signal_type":"power","side":"top","x_px":576,"y_px":46,"aliases":[],"sort_order":14},
    {"slug":"arduino-nano","pin_key":"D12","label":"D12/MISO","signal_type":"spi","side":"bottom","x_px":44,"y_px":174,"aliases":["12","MISO"],"sort_order":100},
    {"slug":"arduino-nano","pin_key":"D11","label":"D11 PWM/MOSI","signal_type":"pwm","side":"bottom","x_px":82,"y_px":174,"aliases":["11","MOSI"],"sort_order":101},
    {"slug":"arduino-nano","pin_key":"D10","label":"D10 PWM/SS","signal_type":"pwm","side":"bottom","x_px":120,"y_px":174,"aliases":["10","SS"],"sort_order":102},
    {"slug":"arduino-nano","pin_key":"D9","label":"D9 PWM","signal_type":"pwm","side":"bottom","x_px":158,"y_px":174,"aliases":["9"],"sort_order":103},
    {"slug":"arduino-nano","pin_key":"D8","label":"D8","signal_type":"digital","side":"bottom","x_px":196,"y_px":174,"aliases":["8"],"sort_order":104},
    {"slug":"arduino-nano","pin_key":"D7","label":"D7","signal_type":"digital","side":"bottom","x_px":234,"y_px":174,"aliases":["7"],"sort_order":105},
    {"slug":"arduino-nano","pin_key":"D6","label":"D6 PWM","signal_type":"pwm","side":"bottom","x_px":272,"y_px":174,"aliases":["6"],"sort_order":106},
    {"slug":"arduino-nano","pin_key":"D5","label":"D5 PWM","signal_type":"pwm","side":"bottom","x_px":310,"y_px":174,"aliases":["5"],"sort_order":107},
    {"slug":"arduino-nano","pin_key":"D4","label":"D4","signal_type":"digital","side":"bottom","x_px":348,"y_px":174,"aliases":["4"],"sort_order":108},
    {"slug":"arduino-nano","pin_key":"D3","label":"D3 PWM","signal_type":"pwm","side":"bottom","x_px":386,"y_px":174,"aliases":["3"],"sort_order":109},
    {"slug":"arduino-nano","pin_key":"D2","label":"D2","signal_type":"digital","side":"bottom","x_px":424,"y_px":174,"aliases":["2"],"sort_order":110},
    {"slug":"arduino-nano","pin_key":"GND_2","label":"GND","signal_type":"ground","side":"bottom","x_px":462,"y_px":174,"aliases":["GND"],"sort_order":111},
    {"slug":"arduino-nano","pin_key":"RESET_2","label":"RESET","signal_type":"digital","side":"bottom","x_px":500,"y_px":174,"aliases":["RST","RESET"],"sort_order":112},
    {"slug":"arduino-nano","pin_key":"D0","label":"D0/RX","signal_type":"uart","side":"bottom","x_px":538,"y_px":174,"aliases":["0","RX"],"sort_order":113},
    {"slug":"arduino-nano","pin_key":"D1","label":"D1/TX","signal_type":"uart","side":"bottom","x_px":576,"y_px":174,"aliases":["1","TX"],"sort_order":114},

    {"slug":"raspberry-pi-4b","pin_key":"P1","label":"1 3.3V","signal_type":"power","side":"top","x_px":142,"y_px":62,"aliases":["3V3"],"sort_order":0},
    {"slug":"raspberry-pi-4b","pin_key":"P2","label":"2 5V","signal_type":"power","side":"bottom","x_px":142,"y_px":90,"aliases":["5V"],"sort_order":1},
    {"slug":"raspberry-pi-4b","pin_key":"P3","label":"3 GPIO2/SDA1","signal_type":"i2c","side":"top","x_px":166,"y_px":62,"aliases":["GPIO2","SDA1"],"sort_order":2},
    {"slug":"raspberry-pi-4b","pin_key":"P4","label":"4 5V","signal_type":"power","side":"bottom","x_px":166,"y_px":90,"aliases":["5V"],"sort_order":3},
    {"slug":"raspberry-pi-4b","pin_key":"P5","label":"5 GPIO3/SCL1","signal_type":"i2c","side":"top","x_px":190,"y_px":62,"aliases":["GPIO3","SCL1"],"sort_order":4},
    {"slug":"raspberry-pi-4b","pin_key":"P6","label":"6 GND","signal_type":"ground","side":"bottom","x_px":190,"y_px":90,"aliases":["GND"],"sort_order":5},
    {"slug":"raspberry-pi-4b","pin_key":"P7","label":"7 GPIO4","signal_type":"gpio","side":"top","x_px":214,"y_px":62,"aliases":["GPIO4"],"sort_order":6},
    {"slug":"raspberry-pi-4b","pin_key":"P8","label":"8 GPIO14/TXD0","signal_type":"uart","side":"bottom","x_px":214,"y_px":90,"aliases":["GPIO14","TXD0"],"sort_order":7},
    {"slug":"raspberry-pi-4b","pin_key":"P9","label":"9 GND","signal_type":"ground","side":"top","x_px":238,"y_px":62,"aliases":["GND"],"sort_order":8},
    {"slug":"raspberry-pi-4b","pin_key":"P10","label":"10 GPIO15/RXD0","signal_type":"uart","side":"bottom","x_px":238,"y_px":90,"aliases":["GPIO15","RXD0"],"sort_order":9},
    {"slug":"raspberry-pi-4b","pin_key":"P11","label":"11 GPIO17","signal_type":"gpio","side":"top","x_px":262,"y_px":62,"aliases":["GPIO17"],"sort_order":10},
    {"slug":"raspberry-pi-4b","pin_key":"P12","label":"12 GPIO18/PWM0","signal_type":"pwm","side":"bottom","x_px":262,"y_px":90,"aliases":["GPIO18","PWM0"],"sort_order":11},
    {"slug":"raspberry-pi-4b","pin_key":"P13","label":"13 GPIO27","signal_type":"gpio","side":"top","x_px":286,"y_px":62,"aliases":["GPIO27"],"sort_order":12},
    {"slug":"raspberry-pi-4b","pin_key":"P14","label":"14 GND","signal_type":"ground","side":"bottom","x_px":286,"y_px":90,"aliases":["GND"],"sort_order":13},
    {"slug":"raspberry-pi-4b","pin_key":"P15","label":"15 GPIO22","signal_type":"gpio","side":"top","x_px":310,"y_px":62,"aliases":["GPIO22"],"sort_order":14},
    {"slug":"raspberry-pi-4b","pin_key":"P16","label":"16 GPIO23","signal_type":"gpio","side":"bottom","x_px":310,"y_px":90,"aliases":["GPIO23"],"sort_order":15},
    {"slug":"raspberry-pi-4b","pin_key":"P17","label":"17 3.3V","signal_type":"power","side":"top","x_px":334,"y_px":62,"aliases":["3V3"],"sort_order":16},
    {"slug":"raspberry-pi-4b","pin_key":"P18","label":"18 GPIO24","signal_type":"gpio","side":"bottom","x_px":334,"y_px":90,"aliases":["GPIO24"],"sort_order":17},
    {"slug":"raspberry-pi-4b","pin_key":"P19","label":"19 GPIO10/MOSI","signal_type":"spi","side":"top","x_px":358,"y_px":62,"aliases":["GPIO10","MOSI"],"sort_order":18},
    {"slug":"raspberry-pi-4b","pin_key":"P20","label":"20 GND","signal_type":"ground","side":"bottom","x_px":358,"y_px":90,"aliases":["GND"],"sort_order":19},
    {"slug":"raspberry-pi-4b","pin_key":"P21","label":"21 GPIO9/MISO","signal_type":"spi","side":"top","x_px":382,"y_px":62,"aliases":["GPIO9","MISO"],"sort_order":20},
    {"slug":"raspberry-pi-4b","pin_key":"P22","label":"22 GPIO25","signal_type":"gpio","side":"bottom","x_px":382,"y_px":90,"aliases":["GPIO25"],"sort_order":21},
    {"slug":"raspberry-pi-4b","pin_key":"P23","label":"23 GPIO11/SCLK","signal_type":"spi","side":"top","x_px":406,"y_px":62,"aliases":["GPIO11","SCLK"],"sort_order":22},
    {"slug":"raspberry-pi-4b","pin_key":"P24","label":"24 GPIO8/CE0","signal_type":"spi","side":"bottom","x_px":406,"y_px":90,"aliases":["GPIO8","CE0"],"sort_order":23},
    {"slug":"raspberry-pi-4b","pin_key":"P25","label":"25 GND","signal_type":"ground","side":"top","x_px":430,"y_px":62,"aliases":["GND"],"sort_order":24},
    {"slug":"raspberry-pi-4b","pin_key":"P26","label":"26 GPIO7/CE1","signal_type":"spi","side":"bottom","x_px":430,"y_px":90,"aliases":["GPIO7","CE1"],"sort_order":25},
    {"slug":"raspberry-pi-4b","pin_key":"P27","label":"27 GPIO0/ID_SD","signal_type":"i2c","side":"top","x_px":454,"y_px":62,"aliases":["GPIO0","ID_SD"],"sort_order":26},
    {"slug":"raspberry-pi-4b","pin_key":"P28","label":"28 GPIO1/ID_SC","signal_type":"i2c","side":"bottom","x_px":454,"y_px":90,"aliases":["GPIO1","ID_SC"],"sort_order":27},
    {"slug":"raspberry-pi-4b","pin_key":"P29","label":"29 GPIO5","signal_type":"gpio","side":"top","x_px":478,"y_px":62,"aliases":["GPIO5"],"sort_order":28},
    {"slug":"raspberry-pi-4b","pin_key":"P30","label":"30 GND","signal_type":"ground","side":"bottom","x_px":478,"y_px":90,"aliases":["GND"],"sort_order":29},
    {"slug":"raspberry-pi-4b","pin_key":"P31","label":"31 GPIO6","signal_type":"gpio","side":"top","x_px":502,"y_px":62,"aliases":["GPIO6"],"sort_order":30},
    {"slug":"raspberry-pi-4b","pin_key":"P32","label":"32 GPIO12/PWM0","signal_type":"pwm","side":"bottom","x_px":502,"y_px":90,"aliases":["GPIO12","PWM0"],"sort_order":31},
    {"slug":"raspberry-pi-4b","pin_key":"P33","label":"33 GPIO13/PWM1","signal_type":"pwm","side":"top","x_px":526,"y_px":62,"aliases":["GPIO13","PWM1"],"sort_order":32},
    {"slug":"raspberry-pi-4b","pin_key":"P34","label":"34 GND","signal_type":"ground","side":"bottom","x_px":526,"y_px":90,"aliases":["GND"],"sort_order":33},
    {"slug":"raspberry-pi-4b","pin_key":"P35","label":"35 GPIO19/PCM_FS","signal_type":"gpio","side":"top","x_px":550,"y_px":62,"aliases":["GPIO19","PCM_FS"],"sort_order":34},
    {"slug":"raspberry-pi-4b","pin_key":"P36","label":"36 GPIO16","signal_type":"gpio","side":"bottom","x_px":550,"y_px":90,"aliases":["GPIO16"],"sort_order":35},
    {"slug":"raspberry-pi-4b","pin_key":"P37","label":"37 GPIO26","signal_type":"gpio","side":"top","x_px":574,"y_px":62,"aliases":["GPIO26"],"sort_order":36},
    {"slug":"raspberry-pi-4b","pin_key":"P38","label":"38 GPIO20/PCM_DIN","signal_type":"gpio","side":"bottom","x_px":574,"y_px":90,"aliases":["GPIO20","PCM_DIN"],"sort_order":37},
    {"slug":"raspberry-pi-4b","pin_key":"P39","label":"39 GND","signal_type":"ground","side":"top","x_px":598,"y_px":62,"aliases":["GND"],"sort_order":38},
    {"slug":"raspberry-pi-4b","pin_key":"P40","label":"40 GPIO21/PCM_DOUT","signal_type":"gpio","side":"bottom","x_px":598,"y_px":90,"aliases":["GPIO21","PCM_DOUT"],"sort_order":39},

    {"slug":"led-5mm-red","pin_key":"ANODE","label":"Anode +","signal_type":"component","side":"bottom","x_px":66,"y_px":198,"aliases":["A","+"],"sort_order":0},
    {"slug":"led-5mm-red","pin_key":"CATHODE","label":"Cathode -","signal_type":"ground","side":"bottom","x_px":96,"y_px":198,"aliases":["K","-"],"sort_order":1},
    {"slug":"resistor-220ohm","pin_key":"A","label":"Lead A","signal_type":"component","side":"left","x_px":18,"y_px":46,"aliases":[],"sort_order":0},
    {"slug":"resistor-220ohm","pin_key":"B","label":"Lead B","signal_type":"component","side":"right","x_px":282,"y_px":46,"aliases":[],"sort_order":1},

    {"slug":"hc-sr04","pin_key":"VCC","label":"VCC","signal_type":"power","side":"bottom","x_px":126,"y_px":142,"aliases":["5V"],"sort_order":0},
    {"slug":"hc-sr04","pin_key":"TRIG","label":"TRIG","signal_type":"digital","side":"bottom","x_px":160,"y_px":142,"aliases":[],"sort_order":1},
    {"slug":"hc-sr04","pin_key":"ECHO","label":"ECHO","signal_type":"digital","side":"bottom","x_px":195,"y_px":142,"aliases":[],"sort_order":2},
    {"slug":"hc-sr04","pin_key":"GND","label":"GND","signal_type":"ground","side":"bottom","x_px":230,"y_px":142,"aliases":[],"sort_order":3},

    {"slug":"servo-sg90","pin_key":"SIGNAL","label":"Signal","signal_type":"pwm","side":"right","x_px":226,"y_px":92,"aliases":["SIG","PWM","orange","yellow"],"sort_order":0},
    {"slug":"servo-sg90","pin_key":"VCC","label":"VCC","signal_type":"power","side":"right","x_px":226,"y_px":124,"aliases":["5V","red"],"sort_order":1},
    {"slug":"servo-sg90","pin_key":"GND","label":"GND","signal_type":"ground","side":"right","x_px":226,"y_px":156,"aliases":["brown","black"],"sort_order":2},

    {"slug":"pushbutton-6x6","pin_key":"A1","label":"A1","signal_type":"component","side":"left","x_px":38,"y_px":36,"aliases":["left-top"],"sort_order":0},
    {"slug":"pushbutton-6x6","pin_key":"A2","label":"A2","signal_type":"component","side":"left","x_px":38,"y_px":114,"aliases":["left-bottom"],"sort_order":1},
    {"slug":"pushbutton-6x6","pin_key":"B1","label":"B1","signal_type":"component","side":"right","x_px":132,"y_px":36,"aliases":["right-top"],"sort_order":2},
    {"slug":"pushbutton-6x6","pin_key":"B2","label":"B2","signal_type":"component","side":"right","x_px":132,"y_px":114,"aliases":["right-bottom"],"sort_order":3},

    {"slug":"dht11","pin_key":"VCC","label":"VCC","signal_type":"power","side":"bottom","x_px":50,"y_px":196,"aliases":["3V3","5V"],"sort_order":0},
    {"slug":"dht11","pin_key":"DATA","label":"DATA","signal_type":"digital","side":"bottom","x_px":80,"y_px":196,"aliases":[],"sort_order":1},
    {"slug":"dht11","pin_key":"NC","label":"NC","signal_type":"component","side":"bottom","x_px":110,"y_px":196,"aliases":[],"sort_order":2},
    {"slug":"dht11","pin_key":"GND","label":"GND","signal_type":"ground","side":"bottom","x_px":140,"y_px":196,"aliases":[],"sort_order":3},

    {"slug":"breadboard-half","pin_key":"RAIL_TOP_POS","label":"+ top","signal_type":"power","side":"top","x_px":80,"y_px":58,"aliases":["+"],"sort_order":0},
    {"slug":"breadboard-half","pin_key":"RAIL_TOP_NEG","label":"- top","signal_type":"ground","side":"top","x_px":80,"y_px":92,"aliases":["-"],"sort_order":1},
    {"slug":"breadboard-half","pin_key":"RAIL_BOTTOM_POS","label":"+ bottom","signal_type":"power","side":"bottom","x_px":80,"y_px":260,"aliases":["+"],"sort_order":2},
    {"slug":"breadboard-half","pin_key":"RAIL_BOTTOM_NEG","label":"- bottom","signal_type":"ground","side":"bottom","x_px":80,"y_px":294,"aliases":["-"],"sort_order":3},
    {"slug":"breadboard-half","pin_key":"A5","label":"A5","signal_type":"component","side":"center","x_px":236,"y_px":144,"aliases":[],"sort_order":4},
    {"slug":"breadboard-half","pin_key":"J5","label":"J5","signal_type":"component","side":"center","x_px":236,"y_px":204,"aliases":[],"sort_order":5}
  ]
  $$::jsonb) as x(
    slug text,
    pin_key text,
    label text,
    signal_type text,
    side text,
    x_px numeric,
    y_px numeric,
    aliases jsonb,
    sort_order integer
  )
)
insert into public.circuit_component_pins (
  component_id,
  pin_key,
  label,
  signal_type,
  side,
  x_px,
  y_px,
  aliases,
  sort_order
)
select
  assets.id,
  pin_rows.pin_key,
  pin_rows.label,
  pin_rows.signal_type,
  pin_rows.side,
  pin_rows.x_px,
  pin_rows.y_px,
  array(select jsonb_array_elements_text(pin_rows.aliases)),
  pin_rows.sort_order
from pin_rows
join public.circuit_component_assets assets
  on assets.slug = pin_rows.slug
on conflict (component_id, pin_key) do update
set
  label = excluded.label,
  signal_type = excluded.signal_type,
  side = excluded.side,
  x_px = excluded.x_px,
  y_px = excluded.y_px,
  aliases = excluded.aliases,
  sort_order = excluded.sort_order;
